_target_: src.models.LightningRNN.LightningRNN
defaults:
  - network: blstm.yaml
  - loss: loss.yaml
  - spectrogram: spectrogram.yaml
  - inverse_spectrogram: inverse_spectrogram.yaml

learning_rate: 3e-4
