run_name: ${datamodule.source}
description: ${datamodule.source}

defaults:
  - _self_
  - datamodule: Musdb.yaml
  - model: LightningRNN.yaml
  - logger: tensorboard.yaml
  - trainer: trainer.yaml
  - hydra: hydra.yaml
  - paths: paths.yaml
